name: goreleaser

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "New tag name"
        required: true

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: git tag ${{ github.event.inputs.tag }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.11.0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ">=1.22.5"

      # This step usually is not needed because the /ui/dist is pregenerated locally
      # but its here to ensure that each release embeds the latest ui artifacts.
      # If the artificats differs, a "dirty error" is thrown - https://goreleaser.com/errors/dirty/
      - name: Build Comet UI
        run: npm --prefix=./ui ci && npm --prefix=./ui run build

      # - name: Build Templ files
      #   uses: capthiron/templ-generator-action@v1

      - name: Run tests
        run: go test ./...

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
